### ISSUE TITLE
cannot run most_recent_photoset.js - httpClient request has no method 'close'

### ISSUE THREAD

**Issue by eboudrant** [ciaranj/flickrnode#6]
Hello,
I cannot run the most_recent_photoset.js script I have this error when I use my api flickr key :

TypeError: Object # has no method 'close'
    at Request.executeRequest (/mnt/ws/users/eboudrant/45708/lib/request.js:132:13)
    at People.findByUsername (/mnt/ws/users/eboudrant/45708/lib/people.js:6:21)
    at Object. (/mnt/ws/users/eboudrant/45708/examples/most_recent_photoset.js:11:15)

Any idea, did I made a mistake ? 
I used my flicker api key, the url from the request is working fine on flckr.

Thanks

**Comment by eboudrant** [comment]
httpClient request.close() replaced by httpClient request.end()

**Comment by ciaranj** [comment]
I've just merged down an outstanding pull request that fixes this issue, if you're using git  just do a pull and you should be good to go :)
